#!/usr/bin/env bash
# construir-libreria.sh -- assembles lib/ into ONE classic script that defines a
# global, which is how the library is distributed (ADR 0015): a <script src>,
# no bundler and no dependencies.
#
# WHY A BUILD STEP AND NOT ONE HAND-WRITTEN FILE. The ADR leaves both open. The
# build wins on three counts and each one is about something that already exists
# in this repository:
#
#   1. The seam of ADR 0003 is verified PER FILE, by verificar-cortes.mjs -- the
#      rendering side must not contain one word of the transport. Written as a
#      single file, signalling and rendering share a scope and that check has
#      nothing to point at: the invariant of phase 01 would stop being
#      verifiable on the day the library is cut out.
#   2. The tests import the pure functions of both layers as ES modules. One
#      hand-written classic file would force either rewriting the tests or
#      keeping a second export path alongside it.
#   3. The precedent is here already, and the ADR names it: run.sh writes the
#      signalled playlist on every start. A generated artefact is already how
#      this repository runs, so this adds a step to a script that exists rather
#      than a concept.
#
# The cost, said out loud: a file that can go stale. It is answered the same way
# the playlist is -- built on every start by run.sh, gitignored so no stale copy
# can be committed, and stamped with the sources it came from.
#
# The transformation is two substitutions and nothing else: the import lines go
# and the `export ` keyword goes. What guards it is not the regex, it is the
# syntax check at the end: parsed as a classic script, a surviving `import` or
# `export` is a syntax error, and so is a name declared twice across two files.
set -euo pipefail
cd "$(dirname "$0")/.."

GLOBAL=QualabsConcurrentHls
SALIDA=dist/qualabs-concurrent-hls.js
# In dependency order. The entry point goes last.
FUENTES=(lib/signalling.js lib/renderer.js lib/controls.js lib/media.js lib/concurrent-hls.js)

mkdir -p dist
{
  echo "// $SALIDA -- GENERATED by scripts/construir-libreria.sh. Do not edit."
  echo "// The sources are lib/, one file per piece; this is the distributable"
  echo "// form of ADR 0015: one classic script that defines window.$GLOBAL."
  echo "// Built from: ${FUENTES[*]}"
  echo "(function (global) {"
  echo "'use strict';"
  for f in "${FUENTES[@]}"; do
    echo ""
    echo "// ======================================================== $f"
    sed -E -e '/^import[[:space:]]/d' -e 's/^export[[:space:]]+//' "$f"
  done
  echo ""
  echo "global.$GLOBAL = $GLOBAL;"
  echo "})(globalThis);"
} > "$SALIDA"

if /usr/bin/grep -nE '^[[:space:]]*(import|export)[[:space:]]' "$SALIDA"; then
  echo "construir-libreria: module syntax survived in $SALIDA (see the lines above)" >&2
  exit 1
fi

# .cjs and not .js: package.json declares "type": "module", so a .js file would
# be parsed as a module and the check would accept the very thing it is here to
# catch. As a classic script, import/export and a redeclared name are errors.
CHEQUEO="$(mktemp -d)/chequeo.cjs"
cp "$SALIDA" "$CHEQUEO"
node --check "$CHEQUEO"
rm -rf "$(dirname "$CHEQUEO")"

echo "construir-libreria: $SALIDA ($(wc -l < "$SALIDA") lines, global $GLOBAL)"
